#!/usr/bin/env bash

set -euo pipefail

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source "${script_dir}/.dev/common"

commands_dir="${script_dir}/.dev/commands/*"
for c in ${commands_dir}; do
  if [ ! -f "${c}" ]; then
    continue
  fi
  # shellcheck disable=SC1090
  source "${c}"
done

mutagen_enabled=0

function detect_mutagen_support {
  command -v mutagen >/dev/null 2>&1 \
    && command -v mutagen-compose >/dev/null 2>&1 \
    && mutagen_enabled=1
}

use_mutagen=${USE_MUTAGEN:-0}

function print_usage {
  echo "Usage: ./dev [command] [args]"
}

function show_help {
  cat << EOF
The following commands are supported:

./dev create                # Create a new project
./dev start                 # Start the development stack
./dev stop                  # Stop the development stack
./dev rebuild               # Rebuild the images and restart the development stack
./dev clean                 # Reset the stack (including volumes and images)
./dev execute               # Run arbitrary command in a container
./dev mix                   # Run mix commands in the app container
./dev npm                   # Run npm commands in the assets container

To get information about a single command use ./dev [command] --help
EOF
}

function maybe_show_command_help {
  if [ "${1}" == "--help" ]; then
    return
  fi
  local args=${2:-noop}
  if [ "${args}" != "--help" ]; then
    return
  fi
  case ${command} in
    "create")
      print_help_for_create
      ;;
    "start"|"s")
      print_help_for_start
      ;;
    "stop"|"st")
      print_help_for_stop
      ;;
    "rebuild"|"rb")
      print_help_for_rebuild
      ;;
    "clean"|"cl")
      print_help_for_clean
      ;;
    "execute"|"e")
      print_help_for_execute
      ;;
    "mix"|"m")
      print_help_for_mix
      ;;
    "npm"|"n")
      print_help_for_npm
      ;;
    *) echo "No help found for '${command}'"
  esac
  exit 0
}

function main {
  docker_compose="docker compose"
  detect_mutagen_support
  if [[ "${mutagen_enabled}" == "1" ]] && [[ "${use_mutagen}" == "1" ]]; then
    # shellcheck disable=SC2034
    docker_compose="mutagen-compose"
  fi
  local command="${1:-help}"
  local args="${*:2}"
  maybe_show_command_help "${command}" "${args}"
  case ${command} in
    "--help")
      show_help
      ;;
    "create")
      # shellcheck disable=SC2086
      run_create ${args}
      ;;
    "start"|"s")
      run_start
      ;;
    "stop"|"st")
      run_stop
      ;;
    "rebuild"|"rb")
      run_rebuild
      ;;
    "clean"|"cl")
      run_clean
      ;;
    "execute"|"e")
      # shellcheck disable=SC2086
      run_execute ${args}
      ;;
    "mix"|"m")
      # shellcheck disable=SC2086
      run_mix ${args}
      ;;
    "npm"|"n")
      # shellcheck disable=SC2086
      run_npm ${args}
      ;;
    *) print_usage; echo; show_help
  esac
}

main "$@"

