#!/usr/bin/env bash

function run_create {
  if [ $# -eq 0 ]; then
    echo
    echo "No command provided"
    echo
    print_help_for_create
    exit 1
  fi
  check_requirements
  # shellcheck disable=SC2154
  ${docker_compose} stop app
  local command="${*}"
  echo "Running '${command}' in app container"
  run_execute app "${command}"
  cat << EOF
Project was successfully created. Please check the Docker setup for tweaks
fitting your needs.

Happy coding!
EOF
}

function print_help_for_create {
  cat << EOF
# create

The 'create' command checks if the required tools (Docker, optionally Mutagen) are available.
If so it will check and create or load the images needed for the application.

The command expects the arguments to create the project.

An example would be:

./dev create mix new . --app my_app

You can overwrite all files asked for.
EOF
}

