#!/usr/bin/env bash

function run_execute {
  local container_name=${1}
  local command="${*:2}"
  run_detached_command "${container_name}" "bash" "${command}"
}

function print_help_for_execute {
  cat << EOF
# execute [container_name] [args]

shortcut: e

The 'execute' command runs arbitrary commands in the given container.
F.e. you can run './dev execute app "cd assets && yarn add my_dep -D"' to add a javascript library.
EOF
}

