#!/usr/bin/env bash

function run_mix {
  local container_name=app
  local command="${*:-help}"
  run_detached_command ${container_name} "bash" "mix ${command}"
}

function print_help_for_mix {
  cat << EOF
# mix [args]

shortcut: m

The 'mix' command runs mix commands in the app container.
F.e. you can run './dev mix deps.get' to load the defined dependencies.
EOF
}

