#!/usr/bin/env bash

function run_rebuild {
  # shellcheck disable=SC2154
  ${docker_compose} down && ${docker_compose} build --no-cache
}

function print_help_for_rebuild {
  cat << EOF
# rebuild

shortcut: rb

The 'rebuild' command will tear down and rebuild the containers.
The volumes and images will be preserved.
EOF
}

