#!/usr/bin/env bash

function startup {
  echo "Starting stack. This might take a while on the first run."
  # shellcheck disable=SC2154
  ${docker_compose} up --quiet-pull -d
}

function attach_to_app {
  echo "Attaching to the application container. Use Ctrl+p Ctrl+q to leave. Use Ctrl-c (twice) to shutdown the app container."
  # shellcheck disable=SC2154
  docker attach "$(docker compose ps -q app)"
}

function run_start {
  check_requirements
  startup
  attach_to_app
}

function print_help_for_start {
  cat << EOF
# start

shortcut: s

The 'start' command checks if the required tools (Docker, optionally Mutagen) are available.
If so it will check and create or load the images needed for the application.
It starts the application stack with all containers and opens the logs.

Stop the command with ctrl-c. This will stop only the web container.
EOF
}

