#!/usr/bin/env bash

function check_command {
  local command=$1
  if ! command ${command} >/dev/null 2>&1; then
    echo "⨯ ${command} not found"
    echo "Please install ${command}!"
    exit 1
  fi
  echo "✓ ${command} found"
}

function check_requirements {
  check_command "docker"
  check_command "docker-compose"
}

function run_detached_command {
  local container_name=${1}
  local shell=${2}
  local command="${*:3}"
  echo "Running detached command '${command}'"
  # shellcheck disable=SC2154
  ${docker_compose} run --quiet-pull --rm "${container_name}" "${shell}" -c "${command}"
}

