#!/usr/bin/env bash

function run_init {
  local name=${1}
  local pattern="s/template/${name}/g"
  local files=( docker-compose.mutagen.yml mutagen.yml )
  for file in ${files[@]}; do
    tmpFile="${file}.tmp"
    mv ${file} ${tmpFile}
    sed -e ${pattern} ${tmpFile} > ${file}
    rm ${tmpFile}
    echo "${file} updated"
  done

  cat << EOF
Project "${name}" was successfully initialized.

Please run ./dev create to finish setup.
EOF
}

function print_help_for_init {
  cat << EOF
# init NAME

The 'init' command substitutes the placeholder with the actual project name
passed as argument.

An example would be:

./dev init my_app
EOF
}

