#!/usr/bin/env bash

function run_detached_command {
  local container_name=${1}
  local command="${*:2}"
  # shellcheck disable=SC2154
  ${docker_compose} run --rm "${container_name}" bash -c "${command}" 2>/dev/null
}

function run_mix {
  local container_name=app
  local command="${*}"
  run_detached_command ${container_name} "mix ${command}"
}

function print_help_for_mix {
  cat << EOF
# mix [args]

shortcut: m

The 'mix' command runs mix commands in the app container.
F.e. you can run './dev mix deps.get' to load the defined dependencies.
EOF
}

