#!/usr/bin/env bash

function run_detached_command {
  local container_name=${1}
  local command="${*:2}"
  # shellcheck disable=SC2154
  ${docker_compose} run --rm "${container_name}" sh -c "${command}" 2>/dev/null
}

function run_npm {
  local container_name=assets
  local command="${*:--help}"
  run_detached_command ${container_name} "npm ${command}"
}

function print_help_for_npm {
  cat << EOF
# npm [args]

shortcut: n

The 'npm' command runs npm commands in the assets container.
F.e. you can run './dev npm install alpine' to install the defined dependency.

The 'assets' container is a standalone container only used to have the same npm
version installed. It is not running per default.
EOF
}



