#!/usr/bin/env bash

function shutdown {
  echo "Shutting down..."
  if [[ "${MUTAGEN_ENABLED}" == "1" ]]; then
    mutagen project pause
  else
    docker-compose stop
  fi
  echo "done"
}

function run_stop {
  shutdown
}

function print_help_for_stop {
  cat << EOF
# stop

shortcut: st

The 'stop' command will stop the stack. All data and containers will be preserved.
EOF
}

